import './js/fetch';
import './js/modal';
// import './js/pagination-fetch';
import './js/loader';
// import './js/render-top-films';
import './js/scroll';
import './js/switch-theme';
import './js/trailer';
import './js/switchLanguage';
import './js/for-teams';
